name: Build and Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    name: Build - Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Build
        run: cargo build --release

      - name: Rename
        run: mv ./target/release/crypt ./crypt-${{ github.ref_name }}-linux-x86_64

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: crypt-linux
          path: ./crypt-${{ github.ref_name }}-linux-x86_64
          retention-days: 1
    
  build-windows:
    name: Build - Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Build
        run: cargo build --release

      - name: Rename
        run: move ./target/release/crypt.exe ./crypt-${{ github.ref_name }}-windows-x86_64.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: crypt-windows
          path: ./crypt-${{ github.ref_name }}-windows-x86_64.exe
          retention-days: 1

  create_release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]

    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4.2.1
        with:
          name: crypt-linux

      - name: Download Windows artifact
        uses: actions/download-artifact@v4.2.1
        with:
          name: crypt-windows

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.16.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ github.ref_name }}
          tag: ${{ github.ref_name }}
          draft: true
          prerelease: false
          artifacts: "crypt-${{ github.ref_name }}-linux-x86_64, crypt-${{ github.ref_name }}-windows-x86_64.exe"